import { FlexAlignType } from 'react-native';

/*
 *  INTERFACES
 */

export interface TutorialIslandFlowState {
    flow: TutorialIslandFlow;
    currentStepKey: TutorialIslandStepKey;
}

export interface TutorialIslandFlow {
    key: TutorialIslandFlowKey;
    steps: TutorialIslandStep[];
}

export interface TutorialIslandStep {
    key: TutorialIslandStepKey;
    options: TutorialIslandOption[];
}

export interface TutorialIslandOption {
    key: TutorialIslandOptionKey;
    onPressReportable: boolean;
    hidden?: boolean;
    nextFlowKey?: TutorialIslandFlowKey;
    tooltip?: TutorialIslandTooltipData;
}

export interface TutorialIslandTooltipData {
    text: string;
    alignment: FlexAlignType;
    position: TooltipPosition;
    dismissableText?: string;
    padding?: number;
}

/*
 *  ENUMS
 */
export enum TooltipPosition {
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    CENTER = 'CENTER',
}

export enum TutorialIslandFlowKey {
    INVALID = 'INVALID',
    CREATE_HABIT = 'CREATE_HABIT',
    COMPLETE_HABIT = 'COMPLETE_HABIT',
}

export enum TutorialIslandStepKey {
    INVALID = 'INVALID',

    // CREATE HABIT FLOW
    CREATE_HABIT_FLOW__NOTIFY_CREATE_HABIT = 'CREATE_HABIT_FLOW__NOTIFY_CREATE_HABIT',
    CREATE_HABIT_FLOW__PRESS_HABITS_TAB = 'CREATE_HABIT_FLOW__PRESS_HABITS_TAB',
    CREATE_HABIT_FLOW__PRESS_ADD_NEW_HABIT_BUTTON = 'CREATE_HABIT_FLOW__PRESS_ADD_NEW_HABIT_BUTTON',
    CREATE_HABIT_FLOW__EXPLAIN_SET_CORE_INFO = 'CREATE_HABIT_FLOW__EXPLAIN_SET_CORE_INFO',
    CREATE_HABIT_FLOW__EXPLAIN_SET_OPTIONAL_INFO = 'CREATE_HABIT_FLOW__EXPLAIN_SET_OPTIONAL_INFO',
    CREATE_HABIT_FLOW__EXPLAIN_DAYS_OF_THE_WEEK = 'CREATE_HABIT_FLOW__EXPLAIN_DAYS_OF_THE_WEEK',
    CREATE_HABIT_FLOW__EXPLAIN_CREATE = 'CREATE_HABIT_FLOW__EXPLAIN_CREATE',
    CREATE_HABIT_FLOW__ACTION_CREATE = 'CREATE_HABIT_FLOW__ACTION_CREATE',
    CREATE_HABIT_FLOW__EXPLAIN_HABIT_CREATED = 'CREATE_HABIT_FLOW__EXPLAIN_HABIT_CREATED',
    CREATE_HABIT_FLOW__CHANGE_FLOW_TO_COMPLETE_HABIT = 'CREATE_HABIT_FLOW__CHANGE_FLOW_TO_COMPLETE_HABIT',

    // COMPLETE HABIT FLOW
    COMPLETE_HABIT_FLOW__PRESS_TODAY_TAB = 'COMPLETE_HABIT_FLOW__PRESS_TODAY_TAB',
    COMPLETE_HABIT_FLOW__SWIPE_COMPLETE = 'COMPLETE_HABIT_FLOW__SWIPE_COMPLETE',
    COMPLETE_HABIT_FLOW__EXPLAIN_COMPLETE = 'COMPLETE_HABIT_FLOW__EXPLAIN_COMPLETE',
    COMPLETE_HABIT_FLOW__SWIPE_RESET = 'COMPLETE_HABIT_FLOW__SWIPE_RESET',
    COMPLETE_HABIT_FLOW__SWIPE_FAIL = 'COMPLETE_HABIT_FLOW__SWIPE_FAIL',
    COMPLETE_HABIT_FLOW__PRESS_EDIT = 'COMPLETE_HABIT_FLOW__PRESS_EDIT',
    COMPLETE_HABIT_FLOW__EXPLAIN_QUANTITY = 'COMPLETE_HABIT_FLOW__EXPLAIN_QUANTITY',
    COMPLETE_HABIT_FLOW__EXPLAIN_ADVANCED = 'COMPLETE_HABIT_FLOW__EXPLAIN_ADVANCED',
    COMPLETE_HABIT_FLOW__EXPLAIN_UPDATE = 'COMPLETE_HABIT_FLOW__EXPLAIN_UPDATE',
    COMPLETE_HABIT_FLOW__BID_GOODLUCK = 'COMPLETE_HABIT_FLOW__BID_GOODLUCK',
}

export enum TutorialIslandOptionKey {
    INVALID = 'INVALID',

    GENERAL_NOTIFICATION = 'GENERAL_NOTIFICATION',

    TAB__TIMELINE = 'TAB__TIMELINE',
    TAB__MY_HABITS_TAB = 'TAB__MY_HABITS_TAB',
    TAB__TODAY = 'TAB__TODAY',
    TAB__JOURNEY = 'TAB__JOURNEY',
    TAB__PROFILE = 'TAB__PROFILE',

    MY_HABITS__ADD_NEW_HABIT_BUTTON = 'MY_HABITS__ADD_NEW_HABIT_BUTTON',
    MY_HABITS__NO_HABITS_NOTICE = 'MY_HABITS__NO_HABITS_NOTICE',
    MY_HABITS__HABITS_LIST = 'MY_HABITS__HABITS_LIST',

    CREATE_EDIT_HABIT__BACK = 'CREATE_EDIT_HABIT__BACK',
    CREATE_EDIT_HABIT__DISCOVER = 'CREATE_EDIT_HABIT__DISCOVER',
    CREATE_EDIT_HABIT__CHANGE_ICON = 'CREATE_EDIT_HABIT__CHANGE_ICON',
    CREATE_EDIT_HABIT__CHANGE_TITLE = 'CREATE_EDIT_HABIT__CHANGE_TITLE',
    CREATE_EDIT_HABIT__CHANGE_NOTES = 'CREATE_EDIT_HABIT__CHANGE_NOTES',
    CREATE_EDIT_HABIT__DAYS_OF_THE_WEEK_TITLE = 'CREATE_EDIT_HABIT__DAYS_OF_THE_WEEK_TITLE',
    CREATE_EDIT_HABIT__DAYS_OF_THE_WEEK_TOGGLE = 'CREATE_EDIT_HABIT__DAYS_OF_THE_WEEK_TOGGLE',
    CREATE_EDIT_HABIT__SPECIFIC_TIME_OF_DAY_TITLE = 'CREATE_EDIT_HABIT__SPECIFIC_TIME_OF_DAY_TITLE',
    CREATE_EDIT_HABIT__SPECIFIC_TIME_OF_DAY_TOGGLE = 'CREATE_EDIT_HABIT__SPECIFIC_TIME_OF_DAY_TOGGLE',
    CREATE_EDIT_HABIT__DETAILS_TITLE = 'CREATE_EDIT_HABIT__DETAILS_TITLE',
    CREATE_EDIT_HABIT__DETAILS_TOGGLE = 'CREATE_EDIT_HABIT__DETAILS_TOGGLE',
    CREATE_EDIT_HABIT__CREATE_BUTTON = 'CREATE_EDIT_HABIT__CREATE_BUTTON',

    PLAN_DAY__PLANNED_TASK = 'PLAN_DAY_PLANNED_TASK',
    UPDATE_HABIT_MODAL__QUANTITY = 'UPDATE_HABIT_MODAL__QUANTITY',
    UPDATE_HABIT_MODAL__QUANTITY_PLUS = 'UPDATE_HABIT_MODAL__QUANTITY_PLUS',
    UPDATE_HABIT_MODAL__QUANTITY_MINUS = 'UPDATE_HABIT_MODAL__QUANTITY_MINUS',
    UPDATE_HABIT_MODAL__QUANTITY_TITLE = 'UPDATE_HABIT_MODAL__QUANTITY_TITLE',
    UPDATE_HABIT_MODAL__ADVANCED_CHEVRON = 'UPDATE_HABIT_MODAL__ADVANCED_CHEVRON',
    UPDATE_HABIT_MODAL__ADVANCED_UPDATE = 'UPDATE_HABIT_MODAL__ADVANCED_UPDATE',
    UPDATE_HABIT_MODAL__ADVANCED_TIME_OF_DAY = 'UPDATE_HABIT_MODAL__ADVANCED_TIME_OF_DAY',
}

/*
 *  INVALID DEFAULTS
 */

export const INVALID_TUTORIAL_ISLAND_FLOW: TutorialIslandFlow = {
    key: TutorialIslandFlowKey.INVALID,
    steps: [],
};

export const INVALID_TUTORIAL_ISLAND_STEP: TutorialIslandStep = {
    key: TutorialIslandStepKey.INVALID,
    options: [],
};

export const INVALID_TUTORIAL_ISLAND_OPTION: TutorialIslandOption = {
    key: TutorialIslandOptionKey.INVALID,
    onPressReportable: false,
};

export const INVALID_TOOLTIP_DATA: TutorialIslandTooltipData = {
    text: '',
    alignment: 'center',
    position: TooltipPosition.CENTER,
};

export const INVALID_FLOW_STATE: TutorialIslandFlowState = {
    flow: INVALID_TUTORIAL_ISLAND_FLOW,
    currentStepKey: TutorialIslandStepKey.INVALID,
};
