export const USER_SEARCH_WIDTH = "95%";
export const SETTINGS_MENU_ITEM_WIDTH = "95%";

// TIMELINE
export const TIMELINE_CARD_PADDING = 12;
export const TIMELINE_CARD_ICON_SIZE = 25;
export const TIMELINE_CARD_ICON_COUNT_SIZE = 12;