export enum Code {
    SUCCESS,
    UNAUTHORIZED,
    GENERIC_ERROR,

    //CREATE USER
    CREATE_ACCOUNT_EMAIL_IN_USE,
    CREATE_ACCOUNT_INVALID_EMAIL,
    CREATE_ACCOUNT_INVALID_PASSWORD,

    //FORGOT PASSWORD
    FORGOT_ACCOUNT_PASSWORD_INVALID_EMAIL,
    FORGOT_ACCOUNT_PASSWORD_UNKNOWN_EMAIL,

    //SEND_VERIFICATION_EMAIL
    SEND_ACCOUNT_VERIFICATION_EMAIL_UNKNOWN_EMAIL,
    SEND_ACCOUNT_VERIFICATION_EMAIL_INVALID_EMAIL,
    SEND_ACCOUNT_VERIFICATION_EMAIL_TOO_MANY_ATTEMPTS,

    //ACCOUNT AUTHENTICATION
    ACCOUNT_AUTHENTICATION_INVALID_CREDENTIALS

}
