export enum Code {
    SUCCESS,
    GENERIC_ERROR,

    //CREATE USER
    CREATE_USER_EMAIL_IN_USE,
    CREATE_USER_INVALID_EMAIL,
    CREATE_USER_INVALID_PASSWORD,

    //FORGOT PASSWORD
    FORGOT_PASSWORD_INVALID_EMAIL,
    FORGOT_PASSWORD_UNKNOWN_EMAIL
}
