export const BETA_EMAIL_HTML =  "<html>"
    + "<body style=\"background-color:#000000;\">"
    + "<div style=\"background-color:#000000;\">"
    + "<!--[if mso | IE]>"
    + "<table"
    + "align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\""
    + ">"
    + "<tr>"
    + "<td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">"
    + "<![endif]-->"
    + "<div style=\"margin:0px auto;max-width:600px;\">"
    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">"
    + "<tbody>"
    + "<tr>"
    + "<td style=\"direction:ltr;font-size:0px;padding:9px 0px 9px 0px;text-align:center;\">"
    + "<!--[if mso | IE]>"
    + "<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">"
    + "<tr>"
    + "<td"
    + "class=\"\" style=\"vertical-align:top;width:600px;\""
    + ">"
    + "<![endif]-->"
    + "<div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">"
    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">"
    + "<tr>"
    + "<td align=\"left\" style=\"font-size:0px;padding:15px 15px 15px 15px;word-break:break-word;\">"
    + "<div style=\"font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.5;text-align:left;color:#000000;\"><p style=\"font-size: 11px; font-family: Ubuntu, Helvetica, Arial; text-align: center;\"><span style=\"color: #ffffff; font-size: 24px;\">embtr.</span></p></div>"
    + "</td>"
    + "</tr>"
    + "<tr>"
    + "<td align=\"center\" style=\"font-size:0px;padding:0px 0px 0px 0px;word-break:break-word;\">"
    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">"
    + "<tbody>"
    + "<tr>"
    + "<td style=\"width:188px;\">"
    + "<img height=\"188px\" src=\"https://www.embtr.com/static/media/logo.1f32fe76.png\" alt=\"\" style=\"border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;\" width=\"188px\">"
    + "</td>"
    + "</tr>"
    + "</tbody>"
    + "</table>"
    + "</td>"
    + "</tr>"
    + "<tr>"
    + "<td align=\"left\" style=\"font-size:0px;padding:15px 15px 15px 15px;word-break:break-word;\">"
    + "<div style=\"font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.5;text-align:left;color:#000000;\"><p style=\"font-size: 11px; font-family: Ubuntu, Helvetica, Arial; text-align: center;\"><span style=\"color: #ffffff;\">Thank you for your interest in joining the embtr beta!</span><br><span style=\"color: #ffffff;\">&nbsp;</span><br><span style=\"color: #ffffff;\">We will send a follow-up email once we have approved your account for beta access. Please understand that we are slowly releasing beta access as we continue to build embtr. We look forward to achieving dreams together!</span></p>"
    + "<p style=\"font-size: 11px; font-family: Ubuntu, Helvetica, Arial; text-align: center;\">&nbsp;</p>"
    + "<hr>"
    + "<p style=\"font-size: 11px; font-family: Ubuntu, Helvetica, Arial; text-align: center;\"><span style=\"color: #ffffff;\">Follow us on social media to stay up to date on the latest embtr updates!</span></p>"
    + "<p style=\"font-size: 11px; font-family: Ubuntu, Helvetica, Arial; text-align: center;\"><span style=\"color: #ffffff;\"><a style=\"color: #63ff82;\" title=\"instagram\" href=\"https://www.instagram.com/_embtr\" target=\"_blank\" rel=\"noopener\">instagram</a> <span style=\"color: #ffffff;\"> &middot; </span> <a style=\"color: #63ff82;\" title=\"twitter\" href=\"https://www.twitter.com/_embtr\" target=\"_blank\" rel=\"noopener\">twitter</a></span></p></div>"
    + "</td>"
    + "</tr>"
    + "</table>"
    + "</div>"
    + "<!--[if mso | IE]>"
    + "</td>"
    + "</tr>"
    + "</table>"
    + "<![endif]-->"
    + "</td>"
    + "</tr>"
    + "</tbody>"
    + "</table>"
    + "</div>"
    + "<!--[if mso | IE]>"
    + "</td>"
    + "</tr>"
    + "</table>"
    + "<![endif]-->"
    + "</div>"
    + "</body>"
    + "</html>";


    export const BETA_EMAIL_PLAIN =  "Thank you for your interest in joining the embtr beta!\n\nWe will send a follow-up email once we have approved your account for beta access. Please understand that we are slowly releasing beta access as we continue to build embtr. We look forward to achieving dreams together!\n\nFollow us on social media to stay up to date on the latest embtr updates!instagram · twitter";